"""그래프 해설(요청 AE2): '근거 자세히' 대신 그래프를 쉽게 풀어 쓴 개조식 설명. chart_card가 펼치기 '그래프 해설'로 보여 준다.

- what: 내용(한 줄, 개조식)
- read: 읽는 법·주의(module_meta의 limitation을 개조식으로 나눔, 요청 AF1)
- as_of: 데이터 기준일, src: 짧은 출처 — 그래프 아래 한 줄(표본 · 기준일 · 출처)에도 쓴다
- insight: '눈에 띄는 점'을 그래프 표(table)에서 계산하는 방법(analytics.insights). cols = 표의 열 순서
  kind: rank(값 순위) · overlay(전체 + 그중 방산) · split(방산 + 그 외 = 합계) · years(연도별) · network(직무 사전)
  overlap = 한 대상이 여러 항목에 들어가 합계가 표본보다 큼(비중을 합계가 아닌 표본 기준으로 말함)
"""
from content.module_meta import POSTINGS_AS_OF

_PORTAL_SRC = "드론정보포털 사업 분야"
_POST_SRC = "사람인·잡코리아 수집 공고"
_NTIS_SRC = "NTIS 국가 R&D 과제"

_OVERLAY_READ = "초록 막대 = 전체, 살짝 아래 빨강 막대 = 그중 방산 관련(겹쳐 그림, 이어 붙인 것 아님)"

EXPLAIN = {
    "I02": dict(what="드론 기업·기관 수, 활용 분야별",
                read=[_OVERLAY_READ,
                      "한 기업이 여러 분야에 속함 → 막대 합계 > 실제 기업 수",
                      "기업·기관 수 ≠ 일자리 수",
                      "방산 관련 = 원문 직접확인·교차출처·인접 후보 자료가 있는 곳(공식 방산업체 지정과 다름)",
                      "막대·아래 칩 클릭 → 해당 분야의 대표 업무·직무·기업으로 이동"],
                as_of="2024-04-24", src=_PORTAL_SRC,
                insight=dict(kind="overlay", unit="곳", label="분야", overlap=True)),
    "I03": dict(what="국가 R&D 드론 과제 수, 연구 기술별",
                read=[_OVERLAY_READ.replace("방산 관련", "방산 태그 과제"),
                      "한 과제가 여러 기술에 속함 → 막대 합계 > 과제 수",
                      "과제 수 ≠ 채용 수요·기술 중요도 순위",
                      "관련성 낮은 과제 259개 제외. '탐색 범위 과제까지 포함' 켜면 포함",
                      "막대 클릭 → 해당 기술의 활용 분야, 아래 '연구 과제 탐색'으로 이동"],
                as_of="기준연도 2017~2026", src=_NTIS_SRC,
                insight=dict(kind="overlay", unit="개", label="기술", overlap=True, part="방산 태그")),
    "I04": dict(what="연도별 국가 R&D 드론 과제 시작 수, 그중 방산 태그 과제",
                read=["막대 전체 = 그해 시작 과제, 빨강 = 그중 방산 태그 과제",
                      "방산 태그 = 과제 설명에 국방·방산 활용 표현 있음(방위사업 계약 여부 아님)",
                      "연도 = 대표 시작 연도. 최근 연도는 수집 시점까지의 일부 값일 수 있음"],
                as_of="기준연도 2017~2026", src=_NTIS_SRC + " · 방산 태그",
                insight=dict(kind="years", unit="개", cols=(0, 1, 2))),   # 표 열 = 시작 연도, 방산 태그, 합계, 그 외
    "J01": dict(what="직무 사전의 드론 직무 구조(대분류 → 중분류 → 직무)",
                read=["가운데 = 전체, 안쪽 큰 점 = 대분류, 그다음 = 중분류, 바깥 작은 점 = 직무",
                      "빨강 점 = 근무처에 '방산기업'이 적힌 직무(채용 여부 아님)",
                      "점 1개 = 사전에 정리한 역할 1개(일자리 규모 아님)",
                      "근거 구성: 공식 직업·NCS 31개, 공고 사례 20개, 산업·활용 분야에서 도출 158개",
                      "드래그 → 회전, 대분류·중분류 클릭 → 해당 가지만 강조"],
                as_of="2026-09-16 정리", src="드론 직무 사전",
                insight=dict(kind="network")),
    "S04": dict(what="지역별 교육 과정 수(고른 키워드 기준, 없으면 전체)",
                read=["지도 숫자 = 지역별 과정 수(원격 제외), 오른쪽 막대 = 그 지역의 키워드별 과정 수",
                      "여러 지역에서 열리는 과정 → 지역마다 셈",
                      "키워드 = 고용24 수집 검색어. 한 과정에 여러 개일 수 있음",
                      "'시작 전·진행 중' = 오늘 날짜 기준 계산. 실제 모집 여부는 원문 확인",
                      "'전남광주' 회차 = 광주·전남 구분 불가 → 따로 표시"],
                as_of="회차 시작 2026-01-01~2027-01-04", src="고용24 훈련과정·회차",
                insight=dict(kind="rank", unit="개 과정", label="지역")),
    "S03": dict(what="수집 공고의 기술 키워드 언급 수, 분류별 많은 순",
                read=["막대 = 그 키워드를 언급한 공고 수",
                      "한 공고가 여러 키워드 언급 → 비율 합계 100% 초과 가능",
                      "목록에 없는 키워드 = 집계 없음(수요 0 아님)",
                      "막대 클릭 → '채용 키워드로 찾기'에서 관련 교육 검색"],
                as_of=POSTINGS_AS_OF, src=_POST_SRC,
                insight=dict(kind="rank", unit="건", label="키워드")),
    "H01": dict(what="수집 공고 수, 직무별(왼쪽 막대)·지역별(오른쪽 지도)",
                read=["초록 = 공고 수, 빨강 = 그중 방산 관련 기업 공고",
                      "지도 마우스 오버 → 막대가 그 지역 값으로 바뀜, 클릭 → 그 지역 공고만",
                      "공고 직무 분류(15개) ≠ 02 직무 사전(209개) 체계",
                      "0건 = 수집 공고에 없음(채용 없음 아님)"],
                as_of=POSTINGS_AS_OF, src=_POST_SRC,
                insight=dict(kind="split", unit="건", label="직무 분류")),
    "H07": dict(what="직무 구성 비중(%) 비교: 방산 관련 기업 공고 vs 그 외 공고",
                read=["왼쪽 = 그 외 공고, 오른쪽 = 방산 관련 기업 공고. 그룹 크기가 달라 건수 대신 그룹 안 비중",
                      "기업명 미연결 공고 82건 → '그 외'에 포함, 방산 공고가 실제보다 적게 보일 수 있음",
                      "표본 작음 → 한두 건 차이로 비중 크게 변함"],
                as_of=POSTINGS_AS_OF, src=_POST_SRC + " + 조직 방산 관련 자료",
                insight=dict(kind="split", unit="건", label="직무 분류")),
    "H02": dict(what="공고의 경력·학력 조건별 공고 수",
                read=["막대 = 그 조건이 적힌 공고 수. 클릭 → 그 조건으로 공고 필터",
                      "경력 연수 결측 많음(52%) → 범주·원문으로만 봄",
                      "'무관' ≠ '신입 우대'"],
                as_of=POSTINGS_AS_OF, src=_POST_SRC,
                insight=dict(kind="rank", unit="건", label="조건")),
    "C01": dict(what="드론 기업·기관 수, 분야별(01 산업 이해와 같은 계산)",
                read=[_OVERLAY_READ,
                      "한 기업이 여러 분야에 속함 → 막대 합계 > 기업 수",
                      "기업 수 ≠ 일자리 수·채용 가능성",
                      "'기준' 단추 → 채용 기업 수·채용 공고 수로 전환"],
                as_of="2024-04-24", src=_PORTAL_SRC,
                insight=dict(kind="overlay", unit="곳", label="분야", overlap=True)),
    "C01P": dict(what="수집 공고가 연결된(채용 중이던) 기업·기관 수, 분야별",
                 read=[_OVERLAY_READ,
                       f"{POSTINGS_AS_OF} 기준 채용 중 공고를 낸 곳. 공고 기업명–조직명 연결된 경우만",
                       "한 기업이 여러 분야에 속함. 채용 규모 아님"],
                 as_of=POSTINGS_AS_OF, src=_PORTAL_SRC + " + " + _POST_SRC,
                 insight=dict(kind="overlay", unit="곳", label="분야", overlap=True)),
    "C01N": dict(what="기업·기관에 연결된 수집 공고 수, 분야별",
                 read=[_OVERLAY_READ,
                       "여러 분야 기업의 공고 → 분야마다 셈, 합계 > 공고 수",
                       "수집 시점 표본. 채용 규모 아님"],
                 as_of=POSTINGS_AS_OF, src=_PORTAL_SRC + " + " + _POST_SRC,
                 insight=dict(kind="overlay", unit="건", label="분야", overlap=True)),
    "C04": dict(what="방산 관련 기업·기관별 연결된 수집 공고 수",
                read=["막대 = 연결된 수집 공고 수, 빨강 진하기 = 방산 관련 근거 강도",
                      "0건 = 수집 시점·경로에서 공고 미확인(채용 없음 아님)",
                      "공고 기업명–조직명 연결된 경우만"],
                as_of=POSTINGS_AS_OF, src="조직 방산 관련 자료 + " + _POST_SRC,
                insight=dict(kind="rank", unit="건", label="기업·기관", cols=(0, 2))),
    "C04A": dict(what="수집 공고가 연결된 기업·기관, 공고 많은 순",
                 read=["막대 = 연결된 수집 공고 수, 빨강 = 방산 관련 기업·기관",
                       "공고 수 = 수집 시점 표본(채용 규모·가능성 아님)",
                       "공고 기업명–조직명 연결된 경우만"],
                 as_of=POSTINGS_AS_OF, src="조직 + " + _POST_SRC,
                 insight=dict(kind="rank", unit="건", label="기업·기관", cols=(0, 2))),
}
